# Generated by Django 3.2 on 2024-03-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_code',
            new_name='confirmation_code',
        ),
    ]
