# Generated by Django 3.2 on 2024-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240305_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
